// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class SWGameServices
{
        public const string achievement_red_cows_redemption = "CgkI967RzqYEEAIQBQ"; // <GPGSID>
        public const string achievement_its_a_bomb_a_bomb = "CgkI967RzqYEEAIQCA"; // <GPGSID>
        public const string achievement_release_the_cows = "CgkI967RzqYEEAIQAg"; // <GPGSID>
        public const string achievement_apocalypse_cow = "CgkI967RzqYEEAIQAw"; // <GPGSID>
        public const string achievement_purple_rain = "CgkI967RzqYEEAIQBg"; // <GPGSID>
        public const string achievement_a_king_among_the_saviors = "CgkI967RzqYEEAIQCQ"; // <GPGSID>
        public const string achievement_white_fang = "CgkI967RzqYEEAIQBA"; // <GPGSID>
        public const string leaderboard_hall_of_fame = "CgkI967RzqYEEAIQAA"; // <GPGSID>
        public const string achievement_why_cant_i_hold_all_these_cows = "CgkI967RzqYEEAIQBw"; // <GPGSID>

}

